### PR TITLE
Improve performace of secs_to_dhms.

### PR DESCRIPTION
**Pull request by cassioneri**
This change is based on examples 14 and 15 of my paper with @llschneider. As explained in the paper, our technique breaks a data dependency and allows the CPU to concurrently calculate quotient and modulus. The price to pay is that the algorithm only works on a subset of possible values which, in this case, is `[0, 97612919[`. This is not a problem here since we only need it on `[0, SECS_IN_DAY[` = `[0, 86400[`. As far as I know this will be the first library _ever_ to use this algorithm 🙂.

Even though the assembly for the new version has two more instructions than the original's (https://godbolt.org/z/fcbjjdvfd), performance seems better and I got:
```
@cassioneri ➜ /workspaces/datealgo-rs (master) $ cargo criterion --bench basic -- secs_to_dhms --measurement-time 30
   Compiling datealgo v0.1.1 (/workspaces/datealgo-rs)
    Finished bench [optimized] target(s) in 4.94s
secs_to_dhms            time:   [2.8906 ns 2.9024 ns 2.9146 ns]                          
                        change: [-12.245% -11.700% -11.202%] (p = 0.00 < 0.05)
                        Performance has improved.
```

Although tests pass, since I'm not a Rust programmer, please review it with extra care. One assumption that I make (based on C/C++ behaviour) is that casting `n` from `u64` to `u32` yields the same value as resetting the upper 32 bits of `n` or, in other words, it's the same as calculating `n` mod 2^32.

I hope this helps but, please, feel free to make any change you wish (e.g., format, comments, ...) or even, reject the PR altogether.

(BTW: Thank you so much for introducing me to Github Codespaces. This is very cool!)

### CODE REVIEW

**Comment by nakedible** [comment]
Thank you for this improvement! I will review it shortly.

> One assumption that I make (based on C/C++ behaviour) is that casting n from u64 to u32 yields the same value as resetting the upper 32 bits of n or, in other words, it's the same as calculating n mod 2^32.

This is true: https://doc.rust-lang.org/reference/expressions/operator-expr.html#semantics

**Comment by nakedible** [comment]
Performance gains reproduced:
```
secs_to_dhms            time:   [2.7536 ns 2.7579 ns 2.7626 ns]
                        change: [-11.323% -11.160% -10.982%] (p = 0.00 < 0.05)
                        Performance has improved.

secs_to_datetime        time:   [5.8185 ns 5.8292 ns 5.8407 ns]
                        change: [-24.911% -24.801% -24.694%] (p = 0.00 < 0.05)
                        Performance has improved.

systemtime_to_datetime  time:   [14.976 ns 15.037 ns 15.100 ns]
                        change: [-2.6845% -2.2759% -1.8277%] (p = 0.00 < 0.05)
                        Performance has improved.
```
The **11%** improvement on the function itself is nothing to scoff at, but the **25%** improvement on `secs_to_datetime` is really impressive. However, unfortunately ultimately it only translates to **2%** improvement on `systemtime_to_datetime` for some reason. Fickle are the ways of the optimizer.

**Comment by nakedible** [comment]
I reformatted the code and comments a bit in #29, and added missing chore-like duties. Let me know if you object to anything in there.

I also invited you to be a collaborator directly on this repository, as when working in the same repository these changes would not have required a separate pull request. However, this is just an offer, feel free to decline if you don't feel comfortable with it. No responsibilities are associated with it.

**Comment by cassioneri** [comment]
> I also invited you to be a collaborator directly on this repository, as when working in the same repository these changes would not have required a separate pull request. However, this is just an offer, feel free to decline if you don't feel comfortable with it. No responsibilities are associated with it.

Thanks. I gladly accept the invitation but I honestly think that my contribution will be very sparse since I'm not a Rust programmer. Indeed my contribution here amounts to 100% of all Rust code that I've ever written.

**Comment by cassioneri** [comment]
@nakedible I suppose this PR can be closed, since it has been superseded  by #29.

**Comment by nakedible** [comment]
This can be closed, changes in #29.

**Pull request closed without merging**
