### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cassioneri**
Fix typos in documentation.

### CODE REVIEW

**Review by nakedible — CHANGES_REQUESTED** [review]
Thanks for spotting these. I don't know how I can have gotten the name wrong. However, these changes need to be done in the documentation section at the start of `lib.rs`. After that one needs to do `cargo install cargo-readme` and then `cargo readme > README.md` to regenerate the README file. (Regenerating the README file from the documentation should be automated, but I haven't gotten around to doing that just yet.

**Comment by nakedible** [comment]
Also, if you can edit the commit message (with `git commit --amend` or `git rebase -i master`) to have the prefix `doc: `, then the changelog will get generated correctly.

**Comment by cassioneri** [comment]
I end up doing a force push on my remote branch. I hope this is not a problem.

**Comment by nakedible** [comment]
Force pushing is exactly right in this case. In GitHub it is mostly safe as the old commits are not truly lost but can be accessed even after pushing. A common hygiene is to use `git push --force-with-lease` instead of `--force` - but that only matters if the same branch is likely to get commits from multiple people at the same time and you want to avoid accidentally overwriting somebody else's work.

Thank you for the fixes.

**Review by nakedible — APPROVED** [review]

**Pull request merged**
